# Generated by Django 5.2.5 on 2025-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_category_slug_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp-slug'),
            preserve_default=False,
        ),
    ]
